# Generated by Django 6.0 on 2025-12-09 17:15

from django.db import migrations

def add_role(apps, schema_editor):
    Role = apps.get_model('users_app', 'Role')
    Role.objects.get_or_create(name='owner')
    Role.objects.get_or_create(name='seeker')


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_role)
    ]

